name: Deploy to server
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.ARTIFACT_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          sudo apt-get install sshpass

      - name: Deploy to server
        run: |
          sshpass -p '${{ secrets.PSWD }}' ssh -v -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} <<'ENDSSH'
          git clone git@github.com:ysset/strapi-service-api.git
          cd ${{ secrets.STRAPI_APP_PATH }}
          touch .env
          echo ${{ secrets.STRAPI_HOST }}
          echo ${{ secrets.STRAPI_PORT }}
          echo ${{ secrets.STRAPI_APP_KEYS }}
          echo ${{ secrets.STRAPI_API_TOKEN_SALT }}
          echo ${{ secrets.STRAPI_ADMIN_JWT_SECRET }}
          echo ${{ secrets.STRAPI_TRANSFER_TOKEN_SALT }}
          echo ${{ secrets.STRAPI_JWT_SECRET }}
          cat .env
          git checkout dev
          git pull
          npm -g config set user root
          sudo make deploy_headless
          ENDSSH
