name: Deploy to server
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.ARTIFACT_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          sudo apt-get install sshpass

      - name: Deploy to server
        run: |
          sshpass -p '${{ secrets.PSWD }}' ssh -v -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} <<'ENDSSH'
          cd ${{ secrets.STRAPI_APP_PATH }}
          touch .env
          echo HOST=${{ secrets.STRAPI_HOST }} >> .env
          echo PORT=${{ secrets.STRAPI_PORT }} >> .env
          echo APP_KEYS=${{ secrets.STRAPI_APP_KEYS }} >> .env
          echo API_TOKEN_SALT=${{ secrets.STRAPI_API_TOKEN_SALT }} >> .env
          echo ADMIN_JWT_SECRET=${{ secrets.STRAPI_ADMIN_JWT_SECRET }} >> .env
          echo TRANSFER_TOKEN_SALT=${{ secrets.STRAPI_TRANSFER_TOKEN_SALT }} >> .env
          echo JWT_SECRET=${{ secrets.STRAPI_JWT_SECRET }} >> .env

          echo YANDEX_SMTP_HOST=${{ secrets.YANDEX_SMTP_HOST }} >> .env
          echo YANDEX_SMTP_PORT=${{ secrets.YANDEX_SMTP_PORT }} >> .env
          echo YANDEX_SMTP_USER=${{ secrets.YANDEX_SMTP_USER }} >> .env
          echo YANDEX_SMTP_USER_PASS=${{ secrets.YANDEX_SMTP_USER_PASS }} >> .env
          echo YANDEX_SMTP_FROM=${{ secrets.YANDEX_SMTP_FROM }} >> .env
          echo ADMIN_URL=${{ secrets.ADMIN_URL }} >> .env
          cat .env
          git checkout dev
          git pull
          sudo make deploy_headless
          ENDSSH
